start bats/facebook_no_k.bat
start bats/facebook_k_1.bat
start bats/facebook_k_2.bat
start bats/facebook_k_3.bat
start bats/facebook_k_4.bat
start bats/facebook_k_5.bat
start bats/facebook_k_6.bat
start bats/facebook_k_7.bat
start bats/facebook_k_8.bat
start bats/communities_fluid_1.bat
start bats/communities_fluid_2.bat
start bats/communities_fluid_3.bat
start bats/communities_fluid_4.bat
start bats/communities_fluid_5.bat
start bats/communities_fluid_6.bat
start bats/communities_fluid_7.bat
start bats/communities_fluid_8.bat
start bats/communities_louvain.bat
